services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
